### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by rehankalu** [4IRL/urls4irl#113]
Let's try and tackle these together in a working session. Perhaps one at a time, if sufficiently challenging. The hope is that it will make debugging simpler without a ton of console.logs

- [ ] Failure of new UTub creation 
- [ ] Failure of new URL creation
- [ ] Failure of addition of existing tag to URL
- [ ] Failure of addition of new tag to URL
- [ ] Failure of editing URL string
- [ ] Failure of editing URL description

**Comment by GPropersi** [comment]
Combining this with #128

**Comment by GPropersi** [comment]
From #128:

In general, the *Fail() functions are unimplemented. Below is an non-exhaustive list of the remaining errors to be handled, and alternative actions proposed to the user for correction. Completion of this list may require consulting all issued errors from the backend.

- [Attempt to add empty UTub] 
- [Attempt to add UTub name > character limit] 
- [Invalid URL submission attempted (URL does not exist)]
- [Attempt to add URL name > character limit] 
- [Attempt to edit URL name > character limit]

**Comment by GPropersi** [comment]
Errors handled!
