### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by rehankalu** [4IRL/urls4irl#128]
In general, the *Fail() functions are unimplemented. Below is an non-exhaustive list of the remaining errors to be handled, and alternative actions proposed to the user for correction. Completion of this list may require consulting all issued errors from the backend.

- [Attempt to add empty UTub] 
- [Attempt to add UTub name > character limit] 
- [Invalid URL submission attempted (URL does not exist)]
- [Attempt to add URL name > character limit] 
- [Attempt to edit URL name > character limit]

**Comment by GPropersi** [comment]
Closing to let #113 handle this.
