### ISSUE TITLE
Weird URLTitle Error

### ISSUE THREAD

**Issue by rehankalu** [4IRL/urls4irl#158]
Create a new UTub. Add at least 2x URLs. Create or switch to another UTub, and then return. For some reason, the URLTitle of the 1st URL is missing.

If you add just 1x URL, this error does not occur.

**Comment by GPropersi** [comment]
Could this be due to change from `url_description` vs `url_title` somehow?

**Comment by GPropersi** [comment]
UPDATE: When a previously added URL that wasn't associated with the UTub was added to the UTub, then its `url_title` wouldn't get added to the database. I updated this and added a test to confirm. Will push a fix in a bit.
