### ISSUE TITLE
'Enter' key functionality for delete UTub modal submission

### ISSUE THREAD

**Issue by rehankalu** [4IRL/urls4irl#166]
Confirmation modal for UTub deletion does not submit with the 'Enter' key, intended functionality.

**Comment by GPropersi** [comment]
It does, you just have to tab to the delete button and then tab again to the delete button in the modal. Also I think this method is preferable over using a `document.addEventListener` style `Enter` key button event, since the user might not want to actually delete the UTub.

**Comment by GPropersi** [comment]
> It does, you just have to tab to the delete button and then tab again to the delete button in the modal. Also I think this method is preferable over using a `document.addEventListener` style `Enter` key button event, since the user might not want to actually delete the UTub.

Closing based on this comment.
