### ISSUE TITLE
Hamburger minimization of side panels

### ISSUE THREAD

**Issue by agentkalu** [4IRL/urls4irl#19]
Make center "current" UTub panel the focus, and set up for mobile

**Comment by GPropersi** [comment]
Update based on new Figma layout for mobile design - move panels to upper hamburger icon and hide/show accordingly.

https://www.figma.com/design/af2iu8Y1aR6KW3CIHFJSHj/U4I?node-id=0-1&t=o32DdbncpfbD1chC-0
