### ISSUE TITLE
New Tag without URL Relation

### ISSUE THREAD

**Issue by rehankalu** [4IRL/urls4irl#20]
Currently newly created tag must be associated with a URL. It would be nice to have a tag added, in advance, and be later added to URLs at the user's discretion

**Comment by GPropersi** [comment]
This will need a dummy row for each model in the database... For example, a tag requires an association with a URL to be in a UTub. Quick fix would be the dummy rows... or make the URL association not mandatory... I'll have to think if there's a better way.

**Comment by GPropersi** [comment]
1) Remove Tags table -> at a limit of 30 chars per tag, duplication space won't be an issue
2) Add UTubTags table with following fields: PK (integer), FK (UTubID, integer), tagString (varchar(30))
3) Now, associate UTubURLTags with tags by FK to UTubTags, and enforce requirement of FK to UTubTags (not nullable)
