### ISSUE TITLE
User Home Page

### ISSUE THREAD

**Issue by GPropersi** [4IRL/urls4irl#4]
User homepage that gets displayed whenever a user logs in. Should display: 

- [x] All user UTubs
- [x] All URLs contained in those UTubs
- [x] All tags associated with the URLs in each UTub
- [x] All users in each UTub
- [ ] Relevant create/update/delete interfaces for UTubs/URLs/Tags based on user permissions (Moved to separate issue) 
- [x] Information box for a selected URL

**Comment by rehankalu** [comment]
Ought there be a distinction between users in an UTub? Currently test users added have the same abilities as the owner: CRUD URLs, CRD Tags+Users
