### ISSUE TITLE
Tag panel functionality

### ISSUE THREAD

**Issue by rehankalu** [4IRL/urls4irl#49]
Create Tag: Clicking + symbol should add a text input to the Tags list. Submit conditions (enter or blurring/lose focus) while the field is empty should remove the input element and do nothing. Reclicking should refocus on input field. Submit conditions once field has data should submit '/tag/new' post request. On success, create new checkbox (default checked).

Edit Tags: Clicking pencil symbol should replace all tag checkboxes with text input fields, displays x symbols on the right of each, and displays an undo symbol. Clicking the pencil symbol again submits all changes via a looped '/tag/edit' post request. Any empty text fields are deleted tags ('/tag/delete' post request). Clicking undo symbol reverts display to pre-edited tags.

**Comment by GPropersi** [comment]
Ties into #20

**Comment by GPropersi** [comment]
Completed in #334
