### ISSUE TITLE
Inserting new URL before selected URL

### ISSUE THREAD

**Issue by rehankalu** [4IRL/urls4irl#53]
Allow user to adjust the location of the new URL by inserting at selected location

**Comment by GPropersi** [comment]
Before this happens, I think we need a method of formatting the order of URLs - perhaps an additional database fields on the UTubUrls table to allow this to happen. They could then adjust the order AFTER creation (default to last (OR FIRST) slot on creation).

How does that sound? May need some rewording on this issue
